version: 2
jobs:
  build:
    branches:
      only:
        - master
        - cicd
        - mobile_frontend
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: cd mobile_frontend && flutter packages get
      - run: cd mobile_frontend && flutter analyze
      - run: cd mobile_frontend && flutter test
      # - run: flutter -v build apk