FROM golang:1.10.4
WORKDIR /go/src/github.com/arunscape/friends
ARG SERVER
RUN echo "Building server: $SERVER"

RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/google/uuid

COPY . .
RUN go build -o main apps/${SERVER}/main.go
CMD ["./main"]

