version: "3"

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

#### PRODUCTION CONFIGURATIONS ####
  auth-server-prod:
    image: prod_auth_server
    env_file: ./prod.env
    environment:
      - PORT=3000
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:friends.reckhard.ca"
      - "traefik.port=3000"

  msg-server-prod:
    image: prod_msg_server
    env_file: ./prod.env
    environment:
      - PORT=3001
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:msg.friends.reckhard.ca"
      - "traefik.port=3001"

#### DEVELOPMENT CONFIGURATIONS ####
  auth-server-dev:
    image: dev_auth_server
    env_file: ./dev.env
    environment:
      - PORT=5000
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:devfriends.reckhard.ca"
      - "traefik.port=5000"

  msg-server-dev:
    image: dev_msg_server
    env_file: ./dev.env
    environment:
      - PORT=5001
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:msg.devfriends.reckhard.ca"
      - "traefik.port=5001"


#### SPIKE CONFIGURATIONS ####
  auth-server-spike:
    image: spike_auth_server
    env_file: ./spike.env
    environment:
      - PORT=8000
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:jfriends.reckhard.ca"
      - "traefik.port=8000"

  msg-server-spike:
    image: spike_msg_server
    env_file: ./spike.env
    environment:
      - PORT=8001
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:msg.jfriends.reckhard.ca"
      - "traefik.port=8001"
